version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/config/logging:/usr/share/elasticsearch/config/logging
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.1
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200
  fluentd:
    build: "./fluentd"
    container_name: fluentd
    depends_on:
      - elasticsearch
      - mosquitto
    volumes:
      - ./fluentd/log:/fluentd/log
      - ./fluentd/etc/fluent.conf:/fluentd/etc/fluent.conf
  mosquitto:
    image: eclipse-mosquitto:1.6.15
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config
